config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resource :comments, only: [:create]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments

  validates :title, presence: true
  validates :text, presence: true
  validates :title, length: { maximum: 140 }
  validates :text, length: { maximum: 4000 }

  def subject
    title
  end

  def last_comment
    comments.last
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :body, length: { maximum: 400 }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :destroy, :edit, :update]

  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    
      if @article.valid?
        @article.save
        redirect_to @article
      else
        render action: 'new'
      end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

      if @article.update(article_params)
        redirect_to @article
      else
        render action: 'edit'
      end
  end

  def destroy
    Article.find(params[:id]).destroy
    redirect_to articles_url
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
  <p>
    <%= f.label :title %><br/ >
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br/ >
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<div class="row">
  <% @articles.each do |art| %>
    <p class="lead">
      <%= art.title %>
    </p>
    <p>
      <%= art.text %>
    </p>
      <p>
        <button class="btn btn-default" type="submit">
          <%= link_to "Show", article_path(art) %>
        </button> 
        <button class="btn btn-default" type="submit">
          <%= link_to "Edit", edit_article_path(art) %>
        </button>
        <button class="btn btn-default" type="submit">
          <%= link_to "Delete", art, method: :delete, data: {confirm: "You sure?"} %>
        </button>
      </p>
      <hr />
  <% end %>
</div

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
  <% if @article && @article.errors.any? %>
    <p>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
  <p>
    <%= f.label :title %><br/ >
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br/ >
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<div class="row">
  <h1><%= @article.title %></h1>

  <p><%= @article.text %></p>

  <h3>Comments:</h3>
  <% @article.comments.each do |comm| %>
    <i>
      <%= comm.author %> said:
    </i>
    <p>
      <%= comm.body %>
    </p>
    <hr>
  <% end %>

  <button class="btn btn-default" type="submit">
    <%= link_to 'Back', articles_url %>
  </button>
  <button class="btn btn-default" type="submit"> 
    <%= link_to 'Edit', edit_article_url %>
  </button>
  <h3>Add comment:</h3>

  <p>
    <%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <i>Author:</i> <%= current_user.username %>
    </p>
    <p>
      <%= f.label :body %><br/ >
      <%= f.text_area :body %>
    </p>
    <p>
      <button class="btn btn-default" type="submit">
        <%= f.submit %>
      </button>
    </p>
    <% end %>
  </p>
</div>

app/views/contacts/create.html.erb
<p>Thank you</p>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>

<%= form_for :contact, url: contacts_path do |f| %>
  <% if @contact && @contact.errors.any? %>
    <p>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
  <p>
    <%= f.label :email %><br/ >
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :message %><br/ >
    <%= f.text_area :message %>
  </p>
  <p>
    <%= f.submit "Send message" %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Welcome</h1>
<p>Nice to see you here.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link data-require="bootstrap@3.3.7" data-semver="3.3.7" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script data-require="bootstrap@3.3.7" data-semver="3.3.7" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">              
            <li><%= link_to 'Articles', articles_url %></li>
            <li><%= link_to 'New', new_article_url %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if user_signed_in? %>
                <p class="navbar-text">
                  Hello, <%= current_user.username %> 
                </p>
                <p class="navbar-text">
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
                </p>
              <% else %>
                <p class="navbar-text">
                  <%= link_to 'Sign In', new_user_session_path %>
                </p>
              <% end %>
            </li>
          </ul>
        </div>

      </div>
    </nav>

    

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  </div>

</body>

</html>

app/views/pages/about.html.erb
<h2>About us:</h2>

app/views/pages/terms.html.erb
<h2>Terms:</h2>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About:</h1>
<p>This is learning application</p>

app/views/static_pages/terms.html.erb
<% provide(:title, "Terms") %>
<h1>Terms:</h1>
<p>blablabla</p>